
class Locators_q(object):

    _path_question_second_page = "//*[contains(text(), 'Have you traded')]"
    _path_finish_button = '[id=button-step]'
    _path_shares = "//select[@id='form-shares']"
    _path_forex = "//select[@id='form-forex']"
    _path_cfds = "//select[@id='form-cfds']"
    _path_spread_betting = "//select[@id='form-spread_betting']"
    _path_relevante_experience = "//select[@id='form-relevant_experience']"
    _path_trading_platform = "//select[@id='form-trading_accounts']"
    _path_currency = "//select[@id='form-currency']"
    _path_currency_title = "[for='form-currency']"
    _path_annual_income = "//select[@id='form-approx_annual_income']"
    _path_employment_status = "//select[@id='form-employment_status']"
    _path_assets = "//select[@id='form-liquid_savings']"
    _java_script_shares = "document.getElementById('form-shares').setAttribute('style', 'inline-block')"
    _java_script_forex = "document.getElementById('form-forex').setAttribute('style', 'inline-block')"
    _java_script_cfds = "document.getElementById('form-cfds').setAttribute('style', 'inline-block')"
    _java_script_spread_betting = "document.getElementById('form-spread_betting').setAttribute('style', 'inline-block')"
    _java_script_relevante_experience = "document.getElementById('form-relevant_experience').setAttribute('style', 'inline-block')"
    _java_script_trading_platform = "document.getElementById('form-trading_accounts').setAttribute('style', 'inline-block')"
    _java_script_currency = "document.getElementById('form-currency').setAttribute('style', 'inline-block')"
    _java_script_annual_income = "document.getElementById('form-approx_annual_income').setAttribute('style', 'inline-block')"
    _java_script_employment_status = "document.getElementById('form-employment_status').setAttribute('style', 'inline-block')"
    _java_script_assets = "document.getElementById('form-liquid_savings').setAttribute('style', 'inline-block')"
    _read_terms = ".checkbox"
    _new_trading_acount_tab = '#base\.portal\.account-add'
    _last_page_title = "TradeCore - Account"
    _path_error_required = "[class='help-block ng-active']"
    _error_message_required = "THIS FIELD IS REQUIRED"
